name: Generate Book Cover

on:
  repository_dispatch:
    types: [generate-cover]

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      R2_PUBLIC_URL: ${{ secrets.R2_PUBLIC_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install sharp @aws-sdk/client-s3 dotenv tsx

      - name: Generate and Upload Cover
        id: generate_step
        run: |
          TITLE="${{ github.event.client_payload.title }}"
          SUBTEXT="${{ github.event.client_payload.subtext }}"
        
          COVER_URL=$(npx tsx for-github-actions/generate.ts "$TITLE" "$SUBTEXT" | tail -n 1)
          echo "cover_url=$COVER_URL" >> "$GITHUB_OUTPUT"

      - name: Show result
        run: echo "Cover URL = ${{ steps.generate_step.outputs.cover_url }}"
